// Code generated by protoc-gen-go. DO NOT EDIT.
// source: progression-service/proto/progression/progression.proto

package go_micro_srv_progression

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Boss struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bossname             string   `protobuf:"bytes,2,opt,name=bossname,proto3" json:"bossname,omitempty"`
	Raidfilter           string   `protobuf:"bytes,3,opt,name=raidfilter,proto3" json:"raidfilter,omitempty"`
	Imgpath              string   `protobuf:"bytes,4,opt,name=imgpath,proto3" json:"imgpath,omitempty"`
	Killorder            string   `protobuf:"bytes,5,opt,name=killorder,proto3" json:"killorder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boss) Reset()         { *m = Boss{} }
func (m *Boss) String() string { return proto.CompactTextString(m) }
func (*Boss) ProtoMessage()    {}
func (*Boss) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fd0e424149c6c92, []int{0}
}

func (m *Boss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boss.Unmarshal(m, b)
}
func (m *Boss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boss.Marshal(b, m, deterministic)
}
func (m *Boss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boss.Merge(m, src)
}
func (m *Boss) XXX_Size() int {
	return xxx_messageInfo_Boss.Size(m)
}
func (m *Boss) XXX_DiscardUnknown() {
	xxx_messageInfo_Boss.DiscardUnknown(m)
}

var xxx_messageInfo_Boss proto.InternalMessageInfo

func (m *Boss) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Boss) GetBossname() string {
	if m != nil {
		return m.Bossname
	}
	return ""
}

func (m *Boss) GetRaidfilter() string {
	if m != nil {
		return m.Raidfilter
	}
	return ""
}

func (m *Boss) GetImgpath() string {
	if m != nil {
		return m.Imgpath
	}
	return ""
}

func (m *Boss) GetKillorder() string {
	if m != nil {
		return m.Killorder
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fd0e424149c6c92, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Boss                 *Boss    `protobuf:"bytes,2,opt,name=boss,proto3" json:"boss,omitempty"`
	Bosses               []*Boss  `protobuf:"bytes,3,rep,name=bosses,proto3" json:"bosses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fd0e424149c6c92, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetBoss() *Boss {
	if m != nil {
		return m.Boss
	}
	return nil
}

func (m *Response) GetBosses() []*Boss {
	if m != nil {
		return m.Bosses
	}
	return nil
}

func init() {
	proto.RegisterType((*Boss)(nil), "go.micro.srv.progression.Boss")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.progression.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.progression.Response")
}

func init() {
	proto.RegisterFile("progression-service/proto/progression/progression.proto", fileDescriptor_3fd0e424149c6c92)
}

var fileDescriptor_3fd0e424149c6c92 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x4e, 0xf3, 0x30,
	0x10, 0xc7, 0xbf, 0xb4, 0xfd, 0x4a, 0x72, 0x20, 0x86, 0x9b, 0xac, 0x0a, 0x55, 0x55, 0xc4, 0xc0,
	0x82, 0x2b, 0x05, 0x09, 0xf6, 0x32, 0x74, 0x45, 0x66, 0x60, 0x4e, 0x93, 0x23, 0x58, 0x24, 0x71,
	0xf0, 0x99, 0x3e, 0x04, 0x13, 0xaf, 0xc4, 0x9b, 0xa1, 0xb8, 0x84, 0x64, 0x89, 0xe8, 0x94, 0xdc,
	0xfd, 0xee, 0xce, 0xff, 0xff, 0xd9, 0x70, 0xd7, 0x58, 0x53, 0x58, 0x62, 0xd6, 0xa6, 0xbe, 0x66,
	0xb2, 0x7b, 0x9d, 0xd1, 0xba, 0xb1, 0xc6, 0x99, 0xf5, 0x80, 0x0c, 0xff, 0xa5, 0xa7, 0x28, 0x0a,
	0x23, 0x2b, 0x9d, 0x59, 0x23, 0xd9, 0xee, 0xe5, 0x80, 0xc7, 0x1f, 0x01, 0xcc, 0x36, 0x86, 0x19,
	0xcf, 0x61, 0xa2, 0x73, 0x11, 0xac, 0x82, 0xab, 0x48, 0x4d, 0x74, 0x8e, 0x0b, 0x08, 0x77, 0x86,
	0xb9, 0x4e, 0x2b, 0x12, 0x13, 0x9f, 0xfd, 0x8d, 0x71, 0x09, 0x60, 0x53, 0x9d, 0x3f, 0xeb, 0xd2,
	0x91, 0x15, 0x53, 0x4f, 0x07, 0x19, 0x14, 0x70, 0xa2, 0xab, 0xa2, 0x49, 0xdd, 0x8b, 0x98, 0x79,
	0xd8, 0x85, 0x78, 0x01, 0xd1, 0xab, 0x2e, 0x4b, 0x63, 0x73, 0xb2, 0xe2, 0xbf, 0x67, 0x7d, 0x22,
	0x3e, 0x03, 0xd8, 0x92, 0x53, 0xf4, 0xf6, 0x4e, 0xec, 0xe2, 0xcf, 0x00, 0x42, 0x45, 0xdc, 0x98,
	0x9a, 0xa9, 0x1d, 0x99, 0x59, 0x4a, 0x1d, 0x1d, 0x34, 0x86, 0xaa, 0x0b, 0x31, 0x81, 0x59, 0x2b,
	0xcc, 0x8b, 0x3c, 0x4d, 0x96, 0x72, 0xcc, 0xaa, 0x6c, 0x6d, 0x2a, 0x5f, 0x8b, 0xb7, 0x30, 0x6f,
	0xbf, 0xc4, 0x62, 0xba, 0x9a, 0x1e, 0xd1, 0xf5, 0x53, 0x9d, 0x7c, 0x05, 0x80, 0x0f, 0x3d, 0x7c,
	0x3c, 0x5c, 0x01, 0x2a, 0x80, 0x7b, 0xaf, 0xc6, 0x6f, 0xf2, 0x8f, 0x61, 0x8b, 0x78, 0x9c, 0x77,
	0x76, 0xe3, 0x7f, 0xf8, 0x04, 0xd1, 0x96, 0xdc, 0xc6, 0x9f, 0x8b, 0x97, 0xe3, 0x2d, 0xfd, 0xc2,
	0x8e, 0x1b, 0xbc, 0x9b, 0xfb, 0x27, 0x71, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x46, 0xa6, 0xdf,
	0xd0, 0x4d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProgressionService service

type ProgressionServiceClient interface {
	CreateBoss(ctx context.Context, in *Boss, opts ...client.CallOption) (*Response, error)
	GetBosses(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type progressionServiceClient struct {
	c           client.Client
	serviceName string
}

func NewProgressionServiceClient(serviceName string, c client.Client) ProgressionServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.progression"
	}
	return &progressionServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *progressionServiceClient) CreateBoss(ctx context.Context, in *Boss, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProgressionService.CreateBoss", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *progressionServiceClient) GetBosses(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProgressionService.GetBosses", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProgressionService service

type ProgressionServiceHandler interface {
	CreateBoss(context.Context, *Boss, *Response) error
	GetBosses(context.Context, *GetRequest, *Response) error
}

func RegisterProgressionServiceHandler(s server.Server, hdlr ProgressionServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProgressionService{hdlr}, opts...))
}

type ProgressionService struct {
	ProgressionServiceHandler
}

func (h *ProgressionService) CreateBoss(ctx context.Context, in *Boss, out *Response) error {
	return h.ProgressionServiceHandler.CreateBoss(ctx, in, out)
}

func (h *ProgressionService) GetBosses(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ProgressionServiceHandler.GetBosses(ctx, in, out)
}
